apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-wordpress
  labels:
    app: wordpress
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: wpuser
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: wpdb
        ports:
        - containerPort: 3306  
      volumes:
      - name: mysql-data
        hostPath:
          path: /data
